name: Data Preprocessing Automation

on:
  push:
    branches:
      - main
    paths:
      - 'data_raw/**'
      - 'preprocessing/automate_Rinaldi.py'
  workflow_dispatch: # <-- Menambahkan opsi trigger manual

permissions:
  contents: write # <-- Menambahkan izin agar bot bisa melakukan commit/push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn
      
      - name: Run Automation Script
        run: python preprocessing/automate_Rinaldi.py

      - name: Commit and Push Processed Data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add preprocessing/data_processed/
          git commit -m "Auto-update processed dataset via CI" || echo "No changes to commit"
          git push